---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgAehic2UmgAvO9DyOQeSRr8LsKliwrooSQD1eicyVhYCxWI+wPvC4/58PKRJxK95JPxlHYmZaktTxEu/dZPaxed2irb+FvVCszYU4b4nTU7dZA2NiYE9T+siGoLcgpHiUPDRar2mKEYwcP+Q+OODD52gO8CRZlDaLCVAVfTEjDZwdle+Jf0oLRc5xYjGTu7ut/r91bxEQ/MggfYWeeOEx9Ej6Hz7w+jz7jjIrUV6+TgBR6c54tBl2Lo0M0PiIvU7VClNOPdpYUZm1mUuRpkHivVIRGWCTKsqxTsRJAcSVyTbfYrrV+ygkLvXorXj3oIp6vuTjee6HRKZ2E8sCiiiB2gR+aQYkxRy5OV7VqjxEdSXAhmEUhq2Qses61wbiiylVl4dIiU2GNK7zUVTDVUArBg0m9D4WDHmfFF0CEjff1Pz7XhjqvTuR5Z83OI8NVbdDog6yXYVpLviJ3gFZVfRLhEEK374UR4g/QaITiLlUc+QmrQpH0wzNih8EkrIUMIOeAGo0G5VVZnVHT4JjIQM8IofD7MAmuy0Q2MvAzpLZX7cEuR8B8889QAw7jPm211ZM7asGMAYCQGZrni1giiCJSRjsmeHdB0VqrYalj0Vx5AtW85ac4O14R+IRd30dq9yJs66J5R5HM49zGHrFUyYAowb+fzYVw/f2HCUYeq55gtAZPCA/6OyjcIAKIWDH8wCLcNa7WDkdMpKMxg4+ablg==
    username: AgAZismFpx2SSn7MU1fe49zdOs6BKCtkaqSfecqXS827FMzGpsaLnIVyCFz4mk8lUIVt+8PcpftDS+6uw4bkviQutu2DKXKp6lPDS4v/NBhGVMnn0LWI9JZFfdQrlb6bDwHOFAoPaJlOGbYQE06W/MegbFsT+E+kk/tW5zJH/Qs/75EiTci1lzpvF4L3tiqbqUxar7ZbPC0j+q7k6D3ifNUUvnMTjFnIqtymper3eU7vlNdDwicmyFIouAaNu5T2JWFkSVIdLvPOCLku6RjcpciS/kEhTKxQgv0eIgfgtTYW6ttjzwfZEnSvNJ8T022Ex6tVfZBGmrHewpbBZlTqYNJZcBWzSWqUwwKFZW6WqyVT1xIWK5tsESAyJB0ZxevqlRjEjnM2f0vGdlwa7q5ZP8bMT7AqV1RcZZ4dBJekWXqrQy9wcPxj2GaifkqTdTxhbhlVgFaJZsS0XbGB7JWH3hSE+C9I09vYTtvJ5ItxET5C7p1vPM6gYh1dgp24uWlv0F0s3RWWFll597fHVPI9hrW3CCd6bw8yygDZwax3qn0xGiAlMo59QSORNBSw7fxTECSw+bX7j6XSDmpugwP5a1UgzeAo5JnLN5w7Uw2qtolPWwPDHkTywPmX4cblitnnKA23LPCDQCk+SC6houIK3V94NtPirjctU+w9QhUbNLnzlnfjEivNMLtRiGd58XtuKiJznhPfhLYP
  template:
    metadata:
      name: gitea-admin-secret
      namespace: gitea
