---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-admin-secret
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgDEjW2KZuLuwFbp9kxLf8tiLWtJ/yW3zg0nxd4cHuhsH/A5nj9cY4PrOqebaNRXhas3UJIogkMcTdzmj2FIgcZQvJpK7BUqbWqoxA36b1XDolhrY51Uu7KHIK9eVGuM3ffYu4bffh3IZL5C2LDL5He475g66gbc6GKrQxiO1nnbRe2ZtNgDaUgGmYKElRvwQCaVZiuG28lpj6571z01ywXZg6BXtSCGNFBXVkesQi5wTbwoNESdj33vIVzCUsf8xgQnkULzYQujQAJ7+CouCiJeqKUEcypUpMEe7St0tyKjYO/jsIQ+mO4p25/hMroF0hrVbmG2clTM6GPFqegOglx+7GFG4S+buYjGzVVyGFSFB3q/Lzf6vE23/nU3yYLSmXk5Wx6LTDTTi/wcdOS4rxo7NOyZiMSnB8/s3OMm/IvP3EWAFxtIMwY3oU9H5E21iJ7/7aKd/J/tUEcUuGUGiNWOv7h9limrfNgNGoeKHcKVBETOwecpYAn8v6vLbpnGbdtjK99WcuQCrSZzWxXpARPXiNcBC1tfC3kjhC7ghrGt3PT9GbgApjHXvy2n7BG/uFpW5wnOOQGmstJYbgl9ygh5ugqzKVd/R0Z+tdcUFlbu4Uv+CMWxqJAdikbhU/dwP8BnvNQmW7dG7yAFx8X043xdhpECjTv9XSE7p06EgpgO99xHmwRvR4QtNRQ0oa29hpn3P88DaCSEC+8hVm1Vlg==
    rootUser: AgAi/QnnlTpegFDW/Z60+9T+PhFLZ0iGK5dI6lR2dS+GharGCO/pgU2LoHL0JAzAj2NvWesacAAW3G0NJejjVmn9bIiXy9gA4WLh2sWdDCY3fn7r6M7iVRPRpEdeJK2SpU13IG/ZsTdYbMJd2A21sQHQxuTm+2++07ZWJTsABASsW9rRINk0p4ARWoeW6sZEr+s/RxJ0M/HGmtfNcCOfLZ10zwMr3uHBEgemu04YXjaApq6FSE2U2KpqiBxxlGPAerppyaXeADWhGB7T9LCZNE5/VGKW4kYtkP2goRba3howx3+pBJ684FTP92DhOg7SqbXcu0BJwX5xwq9hDvZRuKYZ0BsNyWqrMusrQRBdDfjx2oCLTP3O5FjNB3KuE0kb5bAhHkywjz3yyl/Mfnk0/Vq4jCJRlZnRjodOH5Vze23MNNDPoy2xB8mkbol/FF3lJR35qGjKIlIPop9+f0wullGW1IMdod5xCl+w5/NvyTamApyYqXbWLMbx+t00mRuV5vl6SYuKcIDgCyn7j+HrGLyQu0TFg4KPc7kKJNTjuq1igl+912DEOSNbU6EVcaQgUP4CfsKsPWOC13FtWKY0a9FsozJ6HXPeZpK043elGdqM/c8IFiBRE7TfueriFBPIp4F2DP23RnveLUEzkzvJL0LL1LZx+h8YVn6rT7tpvoC+1l73YCc1fklV9GXBJEvEULOYFJREQg==
  template:
    metadata:
      name: minio-admin-secret
      namespace: minio
