---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAc3LsJ+tbyA7LY/TMzb3tB42pFnRmth9InfRvshBwiNNPSBcR1fkkJba+l561grZt31CPHUap5SMn70reZrbPVITZW7ZzSv6+b6NLw+5UYC3fcWoTOf+Bv0f861U/OtkDEX2nByzPxGXbll2hcFgxAHjHDhJmKBzABPiNB2N4GG6zp4Cd5AYRdOLOAubEJ9uAA2zNpy9Tm10IFv80aGCRp0Q1ZeAtF5jtCHS5OHA2VUTtI4Dp3KTFbV+oPsoFbsFsTFCp4a6U1N3/Wdq3j6DQ52t925Q/nX1RS0OC66pnpsFl27MVPqX9JuUDuQVHk8GCwWb/GVJ0lgFE75BorvhCudmbJSCl/PHskVTOFOrXQLQxiuJg9MOCBu6INQD8TTJaHDykzOmGDKGLoSn+yn6KcujMQ5ltagwBhwJSro4uV+oNNHPh+QJ0bdvtqZX5Nm+R2bhtDfsP9xkJLkrzjzpxS90lrJGk0ZFwcbTbyJQrxqGxmbhoKOufCklWy7JILsD/oFXVdEUGyc1TrCwBkicKohB0wMazjYEtCyTmsKZyXhPQ/707o5XYgMJdVu0PHKGehwMEQF9CsvAWviKZuickhPBEBOL+vkiiF7UN71gwj+R3bFnGa9Kz0FJkI+e4GUrW/eWfNfBZ8DNWRvE4Ew/ma+YoLLLbXgpnDl9pn8+drNyHSKRRFzjwIHq0GBvcuhQmQosLoc4M3dZKYNWe30g==
    admin-user: AgBamc4keOAyjj0jVTCXNjNg8F3i0lz2SsBPkec2vrsvFS8m8OGGQvonA9Cx32JHPJxIuMBYzvGzzy7lx08AQXUN/YbLhrJisYsNPnswC2tRQfi4f388h45BW4xo1cLo3ONbkg2cz8bFcmNuaXMxpk2Su5hMGWKmUxaXfrt7nRkwMbEsCftYUskZD/qaKQLLSk9mV95i5IHxap/W8905rmzI/KnJQXpAXoMKurEP7pwJ2BamlkMD+bCvH3rkghBV2rfj6C0EUlBOmSBpbqQrgtTbyLQ5hzlVod+z5R04rBOpetdd0GBVUnPFebCCoZn6Xcgx2gyb4lTRsuvGQdwh5pWEUKwKAJ6vvHDL2U+r4GOSRub4g1t9ItxZ1JYN3Xz8NEbmiPCnrMcqvrcuF5QKym2mWCz4uNdzji72h0YJz7ih674Ty2/pMPJnTHh1ZKhuRDKDKOh6QF+w/HwJwiD7RZBLjYrJTc6GEi2ZHxgB+tLSaehMmA5YJmdWjABiZpuzB/q/WPSF9//ZXwStvL6JRECNTo/ZQIs3Srjer4ixygLEy28eZrqyhiNAxRuZ5rgzlDzmGa8vtrrXy8bdKJZF1KelSElZEiQurODnLnqA4woSLP5nDC9tdjHUx0BsHVHib3i8U/xWwI36vCkelz+h2H3nGt1Pe+1KOMOsbIziySgltHkfIHpxbmBJsVCKw3YX0ODRxdVuAw==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
